// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SosuWeb.Database;

#nullable disable

namespace SosuWeb.Database.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251229024658_Add_VideoUrl")]
    partial class Add_VideoUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SosuBot.Database.Models.RenderJob", b =>
                {
                    b.Property<int>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("JobId"));

                    b.Property<bool>("IsComplete")
                        .HasColumnType("boolean");

                    b.Property<double>("ProgressPercent")
                        .HasColumnType("double precision");

                    b.Property<int?>("RendererId")
                        .HasColumnType("integer");

                    b.Property<int>("RenderingBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RenderingLastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("RenderingStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplayPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VideoUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("JobId");

                    b.HasIndex("RendererId");

                    b.ToTable("RenderJobs");
                });

            modelBuilder.Entity("SosuBot.Database.Models.Renderer", b =>
                {
                    b.Property<int>("RendererId")
                        .HasColumnType("integer");

                    b.Property<long>("BytesRendered")
                        .HasColumnType("bigint");

                    b.Property<bool>("EncodingWithCPU")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsedCPU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsedGPU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RendererId");

                    b.ToTable("Renderers");
                });

            modelBuilder.Entity("SosuBot.Database.Models.RendererCredentials", b =>
                {
                    b.Property<int>("ClientId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ClientId");

                    b.ToTable("RendererCredentials");

                    b.HasData(
                        new
                        {
                            ClientId = 1234,
                            ClientSecretHash = "AQAAAAIAAYagAAAAEJ4Em39CRb34cIHySVUfu5CzCfxl2OgnbI89kooDxJSAU5Y6/54h7o5jPheh3VZGFQ==",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SosuBot.Database.Models.RenderJob", b =>
                {
                    b.HasOne("SosuBot.Database.Models.Renderer", null)
                        .WithMany("CompletedJobs")
                        .HasForeignKey("RendererId");
                });

            modelBuilder.Entity("SosuBot.Database.Models.Renderer", b =>
                {
                    b.Navigation("CompletedJobs");
                });
#pragma warning restore 612, 618
        }
    }
}
